spring:
  application:
    name: spring-security-jwt-dio

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa

  h2:
    console:
      enabled: true

security:
  config:
    prefix: Bearer
    key: SECRET_KEY
    expiration: 3600000