spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/desenv1
    username: desenv1
    password: desenv1
    driverClassName: com.mysql.cj.jdbc.Driver